spring.application.name=ecommerce
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.datasource.url = jdbc:mysql://my-db.cxqm0m4yc25l.eu-north-1.rds.amazonaws.com:3306/my-db
spring.datasource.username =admin
spring.datasource.password = springstudent11

spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect


#images path
project.images = images
spring.app.tokenExpirationTime = 300000000
spring.app.secretKey = ecommerce2025BBBBBBBBBBBBBBBBBBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVLLLLLLLLLLLLLLLKKKKKKKKKKNNNNNNNNNNNNNNNNNNNN\
  mySecretKeyNNNNNNNNNNNNNNNNNNNNNNNNVVVVVVVVVVVVVVVVVVVVVVV.
spring.app.jwtCookie = myCookie

#Needed if using elastic beanstalk
server.port = 5000


